/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical.billing.system;

import BusinessLogic.clsmed;
import BusinessLogic.clsmedprp;
import BusinessLogic.clsstk;
import BusinessLogic.clsstkprp;
import java.awt.event.ItemEvent;
import java.util.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author Aman
 */
public class Stock extends javax.swing.JInternalFrame {

    /**
     * Creates new form Stock
     */
     List<clsmedprp> k;
    public Stock() throws SQLException {
        initComponents();
        setClosable(true);
        setResizable(false);
        setLocation(300,50);
        setTitle("Stock");
        savebtn.setEnabled(true);
        updbtn.setEnabled(false);
        delbtn.setEnabled(false);
        DateFormat format=new SimpleDateFormat("dd-MM-yyyy");
        DateFormatter df=new DateFormatter(format);
        txtstkmnfdat.setFormatterFactory(new DefaultFormatterFactory(df));
        txtstkexpdat.setFormatterFactory(new DefaultFormatterFactory(df));
        
        DefaultComboBoxModel mod=(DefaultComboBoxModel)cmbmednam.getModel();
        clsmed obj=new clsmed();
        k=obj.disp_med();
        for(clsmedprp p:k)
        {
          mod.addElement(p.getMednam());
        }
        cmbmednam.setModel(mod);
    }
     SimpleDateFormat sm=new SimpleDateFormat("dd-MM-yyyy");
   
     void loaddata()
     {
         try {
             int mcod=k.get(cmbmednam.getSelectedIndex()).getMedcod();
             clsstk obj=new clsstk();
             List<clsstkprp> k1=obj.find_stock_med(mcod);
             DefaultTableModel mod=(DefaultTableModel)jTable1.getModel();
             mod.setRowCount(0);
             for(clsstkprp p:k1)
             {
                 String sd=sm.format(p.getStkdat());
                 String md=sm.format(p.getStkmnfdat());
                 String ed=sm.format(p.getStkexpdat());
                 Object[] rowdata=new Object[6];
                 rowdata[0]=p.getStkcod();
                 rowdata[1]=sd;
                 rowdata[2]=md;
                 rowdata[3]=ed;
                 rowdata[4]=p.getStkqty();
                 rowdata[5]=p.getStkprc();
                 mod.addRow(rowdata);
             }
             jTable1.setModel(mod);
             txtstkexpdat.setText("");
             txtstkmnfdat.setText("");
             txtstkqty.setText("");
             txtstkprc.setText("");
             jTable1.clearSelection();
             savebtn.setEnabled(true);
             updbtn.setEnabled(false); 
             delbtn.setEnabled(false);
         } catch (SQLException ex) {
             Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
         }
     }
     
    void clear()
    {
        txtstkexpdat.setText("");
        txtstkmnfdat.setText("");
        txtstkqty.setText("");
        txtstkprc.setText("");
        cmbmednam.setSelectedIndex(0);
        jTable1.clearSelection();
        savebtn.setEnabled(true);
        updbtn.setEnabled(false);
        delbtn.setEnabled(false); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtstkqty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtstkmnfdat = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtstkexpdat = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtstkprc = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        canbtn = new javax.swing.JButton();
        cmbmednam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        updbtn = new javax.swing.JButton();

        jLabel1.setText("Medicine Name");

        jLabel3.setText("Quantity");

        jLabel4.setText("Stock Mfg. Date");

        jLabel5.setText("Stock Exp. Date");

        jLabel6.setText("Price");

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        delbtn.setText("Delete");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        canbtn.setText("Cancel");
        canbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canbtnActionPerformed(evt);
            }
        });

        cmbmednam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbmednamItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Stock Code", "Stock Date", "Mfg. Date", "Exp. Date", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("[ Date must be in the DD-MM-YYYY format ]");

        updbtn.setText("Update");
        updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(updbtn)
                .addGap(28, 28, 28)
                .addComponent(delbtn)
                .addGap(28, 28, 28)
                .addComponent(canbtn)
                .addGap(188, 188, 188))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtstkmnfdat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbmednam, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstkexpdat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtstkqty, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstkprc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbmednam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtstkqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtstkmnfdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtstkexpdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtstkprc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(delbtn)
                    .addComponent(canbtn)
                    .addComponent(updbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        if(txtstkexpdat.getText().equals("")||
                txtstkmnfdat.getText().equals("")||txtstkprc.getText().equals("")
                ||txtstkqty.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Please fill all fields");
        else
        {
            try {
                clsstk obj=new clsstk();
                clsstkprp objprp=new clsstkprp();
                objprp.setStkmedcod(k.get(cmbmednam.getSelectedIndex()).getMedcod());
                objprp.setStkdat(new Date());
                objprp.setStkqty(Integer.parseInt(txtstkqty.getText()));
                Date mfgdat=new SimpleDateFormat("dd-MM-yyyy").parse(txtstkmnfdat.getText());
                Date expdat=new SimpleDateFormat("dd-MM-yyyy").parse(txtstkexpdat.getText());
                objprp.setStkmnfdat(mfgdat);
                objprp.setStkexpdat(expdat);
                objprp.setStkprc(Float.parseFloat(txtstkprc.getText()));
                obj.insert_stock(objprp);
               loaddata();
            } catch (Exception ex) {
                ex.printStackTrace();
            }    
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
         try {
             idx=jTable1.getSelectedRow();
             scod=(int)jTable1.getValueAt(idx, 0);
             clsstk obj=new clsstk();
             clsstkprp p=new clsstkprp();
             p.setStkcod(scod);
             obj.delete_stock(p);
             loaddata();
         } catch (SQLException ex) {
             Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_delbtnActionPerformed

    private void canbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canbtnActionPerformed
    clear();
    }//GEN-LAST:event_canbtnActionPerformed

    private void cmbmednamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbmednamItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED)
        {
            loaddata();
        }    
    }//GEN-LAST:event_cmbmednamItemStateChanged
int idx,scod;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        savebtn.setEnabled(false);
        updbtn.setEnabled(true);
        delbtn.setEnabled(true);
        try {
             idx=jTable1.getSelectedRow();
             scod=(int)jTable1.getValueAt(idx, 0);
             clsstk obj=new clsstk();
             clsstkprp p=obj.find_stock(scod);
             String sd,md,ed;
             md=sm.format(p.getStkmnfdat());
             ed=sm.format(p.getStkexpdat());
             txtstkexpdat.setText(ed);
             txtstkmnfdat.setText(md);
             txtstkprc.setText(Float.toString(p.getStkprc()));
             txtstkqty.setText(Integer.toString(p.getStkqty()));   
         } catch (SQLException ex) {
             Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
         }
       
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbtnActionPerformed
       if(txtstkmnfdat.getText().equals("")||txtstkexpdat.getText().equals("")||
               txtstkprc.getText().equals("")||txtstkqty.getText().equals(""))
           JOptionPane.showMessageDialog(this, "Please fill all fields");
       else
       {
           try {
                clsstk obj=new clsstk();
                clsstkprp objprp=new clsstkprp();
                objprp.setStkmedcod(k.get(cmbmednam.getSelectedIndex()).getMedcod());
                objprp.setStkcod(scod);
                objprp.setStkdat(new Date());
                objprp.setStkqty(Integer.parseInt(txtstkqty.getText()));
                Date mfgdat=new SimpleDateFormat("dd-MM-yyyy").parse(txtstkmnfdat.getText());
                Date expdat=new SimpleDateFormat("dd-MM-yyyy").parse(txtstkexpdat.getText());
                objprp.setStkmnfdat(mfgdat);
                objprp.setStkexpdat(expdat);
                objprp.setStkprc(Float.parseFloat(txtstkprc.getText()));
                obj.update_stock(objprp);
                loaddata();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
       }
    }//GEN-LAST:event_updbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canbtn;
    private javax.swing.JComboBox<String> cmbmednam;
    private javax.swing.JButton delbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton savebtn;
    private javax.swing.JFormattedTextField txtstkexpdat;
    private javax.swing.JFormattedTextField txtstkmnfdat;
    private javax.swing.JTextField txtstkprc;
    private javax.swing.JTextField txtstkqty;
    private javax.swing.JButton updbtn;
    // End of variables declaration//GEN-END:variables
}
